dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.6
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^13.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/sounds/
    - assets/images/

  # Only include platforms you need
  plugin:
    platforms:
      android:
        package: com.example.ts_reminder
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
