name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Tells the server to run commands inside your app folder
    defaults:
      run:
        working-directory: ./ts_reminder

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.6'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build debug APK
        # 👉 THIS IS THE CHANGED LINE: Now it only builds the small version for your phone
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs
  uses: actions/upload-artifact@v4
  with:
    name: ts-reminder-release-apks
    path: ts_reminder/build/app/outputs/flutter-apk/*.apk
